name: /Users/eoseungyun/Desktop/학교/3-1/응용데이터분석/프로젝트/.conda
channels:
  - conda-forge
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.14=py311h155a34a_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=9.2.0=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.21.3=h237132a_0
  - libcxx=20.1.6=ha82da77_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.0=h286801f_0
  - libffi=3.4.6=h1da3d7d_1
  - liblzma=5.8.1=h39f12f2_1
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.0=h3f77e49_0
  - libzlib=1.3.1=h8359307_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.0=h81ee809_1
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1.1=pyh8b19718_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py311h917b07b_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - python=3.11.12=hc22306f_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.11=7_cp311
  - pyzmq=26.4.0=py311h01f2145_0
  - readline=8.2=h1d1bf99_2
  - setuptools=80.8.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=h892fb3f_2
  - tornado=6.5.1=py311h917b07b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.13.2=pyh29332c3_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - zeromq=4.3.5=hc1bb282_7
  - zipp=3.22.0=pyhd8ed1ab_0
  - pip:
      - attrs==25.3.0
      - beautifulsoup4==4.12.0
      - bs4==0.0.2
      - certifi==2025.4.26
      - chardet==3.0.4
      - charset-normalizer==3.4.2
      - click==8.2.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - filelock==3.18.0
      - fonttools==4.58.1
      - fsspec==2025.5.1
      - gensim==4.3.2
      - googletrans==4.0.0rc1
      - h11==0.9.0
      - h2==3.2.0
      - hf-xet==1.1.3
      - hpack==3.0.0
      - hstspreload==2025.1.1
      - httpcore==0.9.1
      - httpx==0.13.3
      - huggingface-hub==0.32.4
      - hyperframe==5.2.0
      - idna==2.10
      - jinja2==3.1.6
      - joblib==1.5.1
      - jpype1==1.5.2
      - kiwisolver==1.4.8
      - konlpy==0.6.0
      - lxml==5.4.0
      - markupsafe==3.0.2
      - matplotlib==3.7.1
      - mpmath==1.3.0
      - networkx==3.5
      - nltk==3.9.1
      - numpy==1.26.4
      - openpyxl==3.1.2
      - outcome==1.3.0.post0
      - pandas==1.5.3
      - pillow==11.2.1
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.31.0
      - rfc3986==1.5.0
      - safetensors==0.5.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - selenium==4.10.0
      - smart-open==7.1.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.7
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - torch==2.7.1
      - tqdm==4.67.1
      - transformers==4.52.4
      - trio==0.30.0
      - trio-websocket==0.12.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - webdriver-manager==4.0.2
      - websocket-client==1.8.0
      - wordcloud==1.9.3
      - wrapt==1.17.2
      - wsproto==1.2.0
      - xgboost==3.0.5
prefix: /Users/eoseungyun/Desktop/학교/3-1/응용데이터분석/프로젝트/.conda
